content = """
// Resolver généré par Nebula
use juniper::{FieldResult, GraphQLObject};

#[derive(GraphQLObject)]
struct {{name}} {
    id: i32,
    name: String,
}

pub fn resolve() -> FieldResult<{{name}}> {
    Ok({{name}} {
        id: 1,
        name: "Hello, {{name}}!".to_string(),
    })
}
"""